name: Build PySide6 EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build EXE using PyInstaller
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller main.py --onefile --noconsole --name MyApp

      - name: Upload EXE artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: MyApp
          path: dist/MyApp.exe
